FROM tomcat:8.5

#COPY admin.war /usr/local/tomcat/webapps/admin.war
COPY agent.war /usr/local/tomcat/webapps/agent.war
COPY MRA1.0.war /usr/local/tomcat/webapps/MRA1.0.war
#COPY ROOT.war /usr/local/tomcat/webapps/ROOT.war
